# Generated by Django 2.1 on 2020-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=30)),
                ('studentemail', models.CharField(max_length=30)),
                ('studentphone', models.IntegerField()),
                ('studentage', models.IntegerField()),
                ('studentrollno', models.IntegerField()),
                ('studentgender', models.CharField(max_length=1)),
                ('image', models.URLField()),
            ],
        ),
    ]
