# Generated by Django 2.1 on 2020-08-08 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentemail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentgender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentphone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentrollno',
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
