# Generated by Django 2.1 on 2020-08-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200808_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentage',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentemail',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentgender',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentphone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentrollno',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
