# Generated by Django 2.1 on 2020-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentage',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentphone',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentrollno',
            field=models.IntegerField(default=20),
        ),
    ]
