# Generated by Django 2.1 on 2020-08-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentrollno',
            field=models.IntegerField(),
        ),
    ]
