# Generated by Django 2.1 on 2020-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200808_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentage',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentphone',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentrollno',
            field=models.IntegerField(default=''),
        ),
    ]
