# Generated by Django 2.1 on 2020-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentemail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentgender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentname',
            field=models.TextField(),
        ),
    ]
