# Generated by Django 2.1 on 2020-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200811_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='studentage',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentemail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentgender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentphone',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentrollno',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
