# Generated by Django 2.1 on 2020-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200811_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentemail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentgender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentphone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentrollno',
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentname',
            field=models.CharField(max_length=50),
        ),
    ]
